# Generated by Django 6.0.3 on 2026-04-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=11)),
                ('name', models.CharField(max_length=255)),
                ('no_of_guests', models.IntegerField(verbose_name=6)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=5)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory', models.IntegerField(verbose_name=5)),
            ],
        ),
    ]
