# Generated by Django 6.0.3 on 2026-04-22 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_booking_no_of_guests_alter_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
